### ISSUE TITLE
Failed to enable firewalld

### ISSUE THREAD

**Issue by oomichi** [tmurakam/k8s-installer#1]
Ansible k8s-installer is failed like the following if the firewalld service is not installed:
```
TASK [firewall : Enable firewalld] *********************************************
fatal: [node01]: FAILED! => {"changed": false, "msg": "Could not find the requested service firewalld: host"}
fatal: [master]: FAILED! => {"changed": false, "msg": "Could not find the requested service firewalld: host"}
        to retry, use: --limit @/home/centos/k8s-installer/ansible/site.retry
```
The virtual machine image comes from the official CentOS7 site.
So it is better to install necessary rpm packages on the ansible playbook for many environments.

**Comment by oomichi** [comment]
The rpm package name seems firewalld.

**Comment by tmurakam** [comment]
I've fixed the issue. Install firewalld with yum if needed.

**Comment by oomichi** [comment]
Thanks for your quick work!

/close
